// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WX4X5h5kjIBdVK6qlFhjXuIhNCBix7U',
    appId: '1:124912840707:web:9a0fde6e9e60cd6df1de36',
    messagingSenderId: '124912840707',
    projectId: 'todo-full-list',
    authDomain: 'todo-full-list.firebaseapp.com',
    storageBucket: 'todo-full-list.appspot.com',
    measurementId: 'G-DM75K7S502',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuIwOy_zSd58oFQmFWPuAdKlXvMvkdktQ',
    appId: '1:124912840707:android:a1bef1cc1b732e51f1de36',
    messagingSenderId: '124912840707',
    projectId: 'todo-full-list',
    storageBucket: 'todo-full-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwwcollidlqEboi2brkkNQut4sqHA1ILM',
    appId: '1:124912840707:ios:c5ba52f304cca6a2f1de36',
    messagingSenderId: '124912840707',
    projectId: 'todo-full-list',
    storageBucket: 'todo-full-list.appspot.com',
    iosBundleId: 'com.example.todoFullList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwwcollidlqEboi2brkkNQut4sqHA1ILM',
    appId: '1:124912840707:ios:4d6ecbb1f53602d8f1de36',
    messagingSenderId: '124912840707',
    projectId: 'todo-full-list',
    storageBucket: 'todo-full-list.appspot.com',
    iosBundleId: 'com.example.todoFullList.RunnerTests',
  );
}
